version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: classifieds_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
    volumes:
      - ./data:/var/lib/postgresql/data
  online-classifieds:
    image: online-classifieds
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/classifieds_db
