version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: classifieds_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
    volumes:
      - ./data:/var/lib/postgresql/data
