server:
  port: 8080
  servlet:
    context-path: /online-classifieds
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./online-classifieds_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
jwt:
  lifetime: 36000000
#spring: настройка под postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5432/classifieds_db
#    username: root
#    password: 123123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
