server:
  port: 8080
  servlet:
    context-path: /online-classifieds
jwt:
  lifetime: 36000000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classifieds_db
    username: root
    password: 123123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
